export const materials = [
  {
    id: "PLA-BLK-01",
    name: "PLA Black",
    type: "PLA",
    color: "#000000",
    remaining: 750,
    cost: 20.99,
    supplier: "FilamentCo",
    location: "Shelf A, Bin 1",
  },
  {
    id: "PETG-WHT-03",
    name: "PETG White",
    type: "PETG",
    color: "#FFFFFF",
    remaining: 250,
    cost: 22.5,
    supplier: "3D Supply",
    location: "Shelf B, Bin 2",
  },
  {
    id: "ABS-RED-02",
    name: "ABS Red",
    type: "ABS",
    color: "#FF0000",
    remaining: 980,
    cost: 25.0,
    supplier: "FilamentCo",
    location: "DryBox 1",
  },
  {
    id: "ABS-BLU-04",
    name: "ABS Blue",
    type: "ABS",
    color: "#0000FF",
    remaining: 600,
    cost: 25.0,
    supplier: "FilamentCo",
    location: "DryBox 1",
  },
  {
    id: "PVA-NTR-05",
    name: "PVA Natural",
    type: "PVA",
    color: "#F0EAD6",
    remaining: 300,
    cost: 45.0,
    supplier: "3D Supply",
    location: "DryBox 1",
  },
  {
    id: "PC-CLR-06",
    name: "PC Clear",
    type: "PC",
    color: "#FFFFFF",
    remaining: 800,
    cost: 55.0,
    supplier: "FilamentCo",
    location: "DryBox 1",
  },
  {
    id: "RES-GRY-05",
    name: "Standard Resin Grey",
    type: "Resin",
    color: "#808080",
    remaining: 450,
    cost: 35.0,
    supplier: "ResinPros",
    location: "Cabinet 3",
  },
  {
    id: "PLA-GLD-07",
    name: "PLA Silk Gold",
    type: "PLA",
    color: "#D4AF37",
    remaining: 850,
    cost: 24.99,
    supplier: "FilamentCo",
    location: "Shelf A, Bin 2",
  },
  {
    id: "PLA-MBL-08",
    name: "PLA Matte Blue",
    type: "PLA",
    color: "#4682B4",
    remaining: 450,
    cost: 21.99,
    supplier: "3D Supply",
    location: "Shelf A, Bin 3",
  },
  {
    id: "PLA-WD-09",
    name: "PLA Wood",
    type: "PLA",
    color: "#DEB887",
    remaining: 600,
    cost: 29.99,
    supplier: "PolyProps",
    location: "Shelf B, Bin 1",
  },
  {
    id: "PLA-GLW-10",
    name: "PLA Glow-in-the-Dark",
    type: "PLA",
    color: "#E0FFD1",
    remaining: 720,
    cost: 28.5,
    supplier: "FilamentCo",
    location: "Shelf C, Bin 1",
  },
  {
    id: "PLA-MRB-11",
    name: "PLA Marble",
    type: "PLA",
    color: "#EAEAEA",
    remaining: 950,
    cost: 26.0,
    supplier: "3D Supply",
    location: "Shelf A, Bin 2",
  },
  {
    id: "ABS-GRN-12",
    name: "ABS Green",
    type: "ABS",
    color: "#008000",
    remaining: 150,
    cost: 24.0,
    supplier: "FilamentCo",
    location: "DryBox 2",
  },
  {
    id: "ABS-ORN-13",
    name: "ABS Orange",
    type: "ABS",
    color: "#FFA500",
    remaining: 880,
    cost: 25.5,
    supplier: "PolyProps",
    location: "DryBox 1",
  },
  {
    id: "ABS-GRY-14",
    name: "ABS Grey",
    type: "ABS",
    color: "#808080",
    remaining: 320,
    cost: 24.99,
    supplier: "3D Supply",
    location: "DryBox 2",
  },
  {
    id: "ABS-NAT-15",
    name: "ABS Natural",
    type: "ABS",
    color: "#F5F5DC",
    remaining: 990,
    cost: 23.0,
    supplier: "FilamentCo",
    location: "DryBox 1",
  },
  {
    id: "ABS-PNK-16",
    name: "ABS Pink",
    type: "ABS",
    color: "#FFC0CB",
    remaining: 50,
    cost: 25.0,
    supplier: "PolyProps",
    location: "DryBox 2",
  },
  {
    id: "PETG-CLR-17",
    name: "PETG Clear",
    type: "PETG",
    color: "#FFFFFF",
    remaining: 900,
    cost: 23.5,
    supplier: "3D Supply",
    location: "Shelf B, Bin 3",
  },
  {
    id: "PETG-BLK-18",
    name: "PETG Black",
    type: "PETG",
    color: "#000000",
    remaining: 200,
    cost: 22.0,
    supplier: "FilamentCo",
    location: "Shelf B, Bin 3",
  },
  {
    id: "PETG-RED-19",
    name: "PETG Red",
    type: "PETG",
    color: "#FF0000",
    remaining: 780,
    cost: 22.99,
    supplier: "PolyProps",
    location: "Shelf C, Bin 2",
  },
  {
    id: "PETG-BLU-20",
    name: "PETG Blue",
    type: "PETG",
    color: "#0000FF",
    remaining: 550,
    cost: 22.99,
    supplier: "FilamentCo",
    location: "Shelf C, Bin 2",
  },
  {
    id: "PETG-YLW-21",
    name: "PETG Yellow",
    type: "PETG",
    color: "#FFFF00",
    remaining: 120,
    cost: 21.5,
    supplier: "3D Supply",
    location: "Shelf B, Bin 1",
  },
  {
    id: "PLA-PRO-22",
    name: "PLA+ Pro Grey",
    type: "PLA",
    color: "#A9A9A9",
    remaining: 980,
    cost: 27.99,
    supplier: "PolyProps",
    location: "Shelf A, Bin 3",
  },
  {
    id: "PLA-SLV-23",
    name: "PLA Silk Silver",
    type: "PLA",
    color: "#C0C0C0",
    remaining: 650,
    cost: 24.99,
    supplier: "FilamentCo",
    location: "Shelf A, Bin 1",
  },
  {
    id: "ABS-CF-24",
    name: "ABS Carbon Fiber",
    type: "ABS",
    color: "#343434",
    remaining: 400,
    cost: 45.0,
    supplier: "PolyProps",
    location: "DryBox 2",
  },
  {
    id: "PETG-GRN-25",
    name: "PETG Green",
    type: "PETG",
    color: "#228B22",
    remaining: 820,
    cost: 23.0,
    supplier: "3D Supply",
    location: "Shelf C, Bin 1",
  },
  {
    id: "PLA-RNB-26",
    name: "PLA Rainbow",
    type: "PLA",
    color: "#FF00FF",
    remaining: 350,
    cost: 30.0,
    supplier: "FilamentCo",
    location: "Shelf B, Bin 1",
  },
  {
    id: "RES-TGH-BLK-27",
    name: "Tough Resin Black",
    type: "Resin",
    color: "#1A1A1A",
    remaining: 800,
    cost: 55.0,
    supplier: "ResinPros",
    location: "Cabinet 1",
  },
  {
    id: "RES-FLX-CLR-28",
    name: "Flexible Resin Clear",
    type: "Resin",
    color: "#FFFFFF",
    remaining: 300,
    cost: 65.99,
    supplier: "3D Supply",
    location: "Cabinet 1",
  },
  {
    id: "RES-CST-PPL-29",
    name: "Castable Wax Resin Purple",
    type: "Resin",
    color: "#8A2BE2",
    remaining: 450,
    cost: 120.0,
    supplier: "PolyProps",
    location: "Cabinet 2",
  },
  {
    id: "RES-DNT-BGE-30",
    name: "Dental Model Resin Beige",
    type: "Resin",
    color: "#F5F5DC",
    remaining: 950,
    cost: 95.5,
    supplier: "ResinPros",
    location: "Cabinet 2",
  },
  {
    id: "RES-HT-AMB-31",
    name: "High Temp Resin Amber",
    type: "Resin",
    color: "#FFBF00",
    remaining: 250,
    cost: 150.0,
    supplier: "3D Supply",
    location: "Cabinet 1",
  },
  {
    id: "RES-WW-WHT-32",
    name: "Water Washable Resin White",
    type: "Resin",
    color: "#FAFAFA",
    remaining: 880,
    cost: 38.0,
    supplier: "FilamentCo",
    location: "Cabinet 4",
  },
  {
    id: "RES-ABS-GRY-33",
    name: "ABS-Like Resin Grey",
    type: "Resin",
    color: "#A9A9A9",
    remaining: 150,
    cost: 42.0,
    supplier: "PolyProps",
    location: "Cabinet 4",
  },
  {
    id: "RES-ECO-GRN-34",
    name: "Plant-based Eco Resin Green",
    type: "Resin",
    color: "#98FB98",
    remaining: 700,
    cost: 39.99,
    supplier: "3D Supply",
    location: "Cabinet 5",
  },
  {
    id: "RES-8K-GRY-35",
    name: "8K Aqua Resin Grey",
    type: "Resin",
    color: "#708090",
    remaining: 980,
    cost: 58.0,
    supplier: "ResinPros",
    location: "Cabinet 5",
  },
  {
    id: "RES-FST-RED-36",
    name: "Fast Curing Resin Red",
    type: "Resin",
    color: "#DC143C",
    remaining: 400,
    cost: 36.5,
    supplier: "FilamentCo",
    location: "Cabinet 4",
  },
]

const p1pLoadedMaterials = [
  // P1P-01
  [
    { slot: 1, materialId: "PLA-BLK-01", remaining: 1000 },
    { slot: 2, materialId: "PLA-MBL-08", remaining: 1000 },
    { slot: 3, materialId: "PLA-SLV-23", remaining: 650 },
    { slot: 4, materialId: "PVA-NTR-05", remaining: 300 },
  ],
  // P1P-02
  [
    { slot: 1, materialId: "PETG-BLK-18", remaining: 1000 },
    { slot: 2, materialId: "PETG-WHT-03", remaining: 1000 },
    { slot: 3, materialId: "PETG-CLR-17", remaining: 900 },
  ],
  // P1P-03
  [
    { slot: 1, materialId: "ABS-RED-02", remaining: 980 },
    { slot: 2, materialId: "ABS-BLU-04", remaining: 600 },
    { slot: 3, materialId: "ABS-GRN-12", remaining: 150 },
    { slot: 4, materialId: "ABS-GRY-14", remaining: 320 },
  ],
  // P1P-04
  [{ slot: 1, materialId: "PLA-RNB-26", remaining: 1000 }],
  // P1P-05
  [
    { slot: 1, materialId: "PLA-PRO-22", remaining: 980 },
    { slot: 2, materialId: "ABS-CF-24", remaining: 400 },
  ],
  // P1P-06
  [
    { slot: 1, materialId: "PETG-RED-19", remaining: 780 },
    { slot: 2, materialId: "PETG-BLU-20", remaining: 550 },
    { slot: 3, materialId: "PETG-GRN-25", remaining: 820 },
    { slot: 4, materialId: "PETG-YLW-21", remaining: 120 },
  ],
  // P1P-07
  [
    { slot: 1, materialId: "PLA-GLD-07", remaining: 850 },
    { slot: 2, materialId: "PLA-SLV-23", remaining: 1000 },
  ],
  // P1P-08
  [
    { slot: 1, materialId: "ABS-ORN-13", remaining: 880 },
    { slot: 2, materialId: "ABS-PNK-16", remaining: 1000 },
  ],
  // P1P-09
  [
    { slot: 1, materialId: "PLA-WD-09", remaining: 600 },
    { slot: 2, materialId: "PLA-MRB-11", remaining: 950 },
  ],
  // P1P-10
  [{ slot: 1, materialId: "PLA-GLW-10", remaining: 720 }],
  // P1P-11
  [
    { slot: 1, materialId: "PLA-BLK-01", remaining: 750 },
    { slot: 2, materialId: "PETG-WHT-03", remaining: 250 },
  ],
  // P1P-12
  [
    { slot: 1, materialId: "ABS-RED-02", remaining: 1000 },
    { slot: 2, materialId: "ABS-BLU-04", remaining: 1000 },
    { slot: 3, materialId: "ABS-GRN-12", remaining: 1000 },
    { slot: 4, materialId: "ABS-ORN-13", remaining: 1000 },
  ],
  // P1P-13
  [
    { slot: 1, materialId: "PETG-BLK-18", remaining: 200 },
    { slot: 2, materialId: "PETG-RED-19", remaining: 1000 },
  ],
  // P1P-14
  [{ slot: 1, materialId: "PC-CLR-06", remaining: 800 }],
  // P1P-15
  [
    { slot: 1, materialId: "PLA-PRO-22", remaining: 1000 },
    { slot: 2, materialId: "PLA-PRO-22", remaining: 1000 },
  ],
  // P1P-16
  [], // Empty
  // P1P-17
  [
    { slot: 1, materialId: "PLA-BLK-01", remaining: 1000 },
    { slot: 2, materialId: "PLA-MBL-08", remaining: 450 },
  ],
  // P1P-18
  [
    { slot: 1, materialId: "PETG-WHT-03", remaining: 1000 },
    { slot: 2, materialId: "PETG-CLR-17", remaining: 1000 },
    { slot: 3, materialId: "PETG-BLK-18", remaining: 1000 },
  ],
  // P1P-19
  [
    { slot: 1, materialId: "ABS-GRY-14", remaining: 1000 },
    { slot: 2, materialId: "ABS-NAT-15", remaining: 990 },
  ],
  // P1P-20
  [], // Empty
]

export const machines = [
  {
    id: "BAMBU-X1C-01",
    name: "Bambu Lab X1C",
    status: "Printing",
    website: "https://bambulab.com/en/x1",
    printHours: 1245,
    maintenance: {
      next: 55, // hours
      last: "2025-06-15",
    },
    bed: {
      type: "Cool Plate / PEI Sheet",
      size: "256x256mm",
    },
    nozzles: {
      current: "0.4mm Hardened Steel",
      available: ["0.2mm", "0.6mm", "0.8mm"],
    },
    currentPrint: {
      file: "multi_color_benchy.3mf",
      image: "/3d-benchy-boat.png",
      progress: 75,
      timeElapsed: "3h 45m",
      timeRemaining: "1h 15m",
    },
    loadedMaterials: [
      { slot: 1, materialId: "ABS-RED-02", remaining: 920 },
      { slot: 2, materialId: "ABS-BLU-04", remaining: 550 },
      { slot: 3, materialId: "PVA-NTR-05", remaining: 280 },
      { slot: 4, materialId: "PC-CLR-06", remaining: 750 },
    ],
    usageHistory: [
      { day: "Mon", hours: 8 },
      { day: "Tue", hours: 12 },
      { day: "Wed", hours: 16 },
      { day: "Thu", hours: 10 },
      { day: "Fri", hours: 20 },
      { day: "Sat", hours: 22 },
      { day: "Sun", hours: 18 },
    ],
  },
  {
    id: "PRUSA-MK3S-02",
    name: "Prusa MK3S+",
    status: "Idle",
    website: "https://www.prusa3d.com/product/original-prusa-i3-mk3s-kit-3/",
    printHours: 3580,
    maintenance: {
      next: 120,
      last: "2025-05-20",
    },
    bed: {
      type: "Smooth PEI Sheet",
      size: "250x210mm",
    },
    nozzles: {
      current: "0.4mm Brass",
      available: ["0.25mm", "0.6mm", "0.8mm"],
    },
    currentPrint: null,
    loadedMaterials: [{ slot: 1, materialId: "PETG-WHT-03", remaining: 250 }],
    usageHistory: [
      { day: "Mon", hours: 4 },
      { day: "Tue", hours: 6 },
      { day: "Wed", hours: 5 },
      { day: "Thu", hours: 8 },
      { day: "Fri", hours: 7 },
      { day: "Sat", hours: 10 },
      { day: "Sun", hours: 9 },
    ],
  },
  {
    id: "ENDER-3-V2-01",
    name: "Ender 3 V2",
    status: "Maintenance",
    website: "https://www.creality.com/products/ender-3-v2-3d-printer",
    printHours: 5120,
    maintenance: {
      next: 0,
      last: "2025-06-28",
    },
    bed: {
      type: "Carborundum Glass",
      size: "220x220mm",
    },
    nozzles: {
      current: "0.4mm Brass",
      available: ["0.2mm", "0.6mm"],
    },
    currentPrint: null,
    loadedMaterials: [],
    usageHistory: [
      { day: "Mon", hours: 14 },
      { day: "Tue", hours: 10 },
      { day: "Wed", hours: 12 },
      { day: "Thu", hours: 15 },
      { day: "Fri", hours: 11 },
      { day: "Sat", hours: 8 },
      { day: "Sun", hours: 9 },
    ],
  },
  {
    id: "SATURN-4K-01",
    name: "Elegoo Saturn 4K",
    status: "Idle",
    website: "https://www.elegoo.com/products/elegoo-saturn-4k-mono-lcd-3d-printer",
    printHours: 850,
    maintenance: {
      next: 250,
      last: "2025-06-01",
    },
    bed: {
      type: "Build Plate",
      size: "192x120mm",
    },
    nozzles: {
      current: "N/A (Resin)",
      available: [],
    },
    currentPrint: null,
    loadedMaterials: [{ slot: 1, materialId: "RES-GRY-05", remaining: 450 }],
    usageHistory: [
      { day: "Mon", hours: 2 },
      { day: "Tue", hours: 3 },
      { day: "Wed", hours: 4 },
      { day: "Thu", hours: 2 },
      { day: "Fri", hours: 5 },
      { day: "Sat", hours: 6 },
      { day: "Sun", hours: 4 },
    ],
  },
  // Start of new P1P data
  {
    id: "BAMBU-P1P-01",
    name: "Bambu Lab P1P #1",
    status: "Printing",
    website: "https://bambulab.com/en/p1p",
    printHours: 250,
    maintenance: { next: 150, last: "2025-06-10" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: {
      file: "voron_v0_parts.3mf",
      image: "/voron-parts.png",
      progress: 62,
      timeElapsed: "8h 12m",
      timeRemaining: "5h 2m",
    },
    loadedMaterials: [
      { slot: 1, materialId: "ABS-RED-02", remaining: 750 },
      { slot: 2, materialId: "ABS-BLU-04", remaining: 600 },
    ],
    usageHistory: [
      { day: "Mon", hours: 18 },
      { day: "Tue", hours: 22 },
      { day: "Wed", hours: 15 },
      { day: "Thu", hours: 20 },
      { day: "Fri", hours: 24 },
      { day: "Sat", hours: 10 },
      { day: "Sun", hours: 5 },
    ],
  },
  {
    id: "BAMBU-P1P-02",
    name: "Bambu Lab P1P #2",
    status: "Printing",
    website: "https://bambulab.com/en/p1p",
    printHours: 120,
    maintenance: { next: 80, last: "2025-06-25" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: {
      file: "articulated_axolotl.3mf",
      image: "/articulated-axolotl.png",
      progress: 85,
      timeElapsed: "4h 30m",
      timeRemaining: "0h 45m",
    },
    loadedMaterials: [{ slot: 1, materialId: "PLA-RNB-26", remaining: 210 }],
    usageHistory: [
      { day: "Mon", hours: 10 },
      { day: "Tue", hours: 15 },
      { day: "Wed", hours: 12 },
      { day: "Thu", hours: 18 },
      { day: "Fri", hours: 20 },
      { day: "Sat", hours: 22 },
      { day: "Sun", hours: 23 },
    ],
  },
  {
    id: "BAMBU-P1P-03",
    name: "Bambu Lab P1P #3",
    status: "Idle",
    website: "https://bambulab.com/en/p1p",
    printHours: 310,
    maintenance: { next: 90, last: "2025-06-01" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: null,
    loadedMaterials: [
      { slot: 1, materialId: "PETG-BLK-18", remaining: 200 },
      { slot: 2, materialId: "PETG-WHT-03", remaining: 250 },
    ],
    usageHistory: [
      { day: "Mon", hours: 24 },
      { day: "Tue", hours: 20 },
      { day: "Wed", hours: 18 },
      { day: "Thu", hours: 22 },
      { day: "Fri", hours: 15 },
      { day: "Sat", hours: 10 },
      { day: "Sun", hours: 11 },
    ],
  },
  {
    id: "BAMBU-P1P-04",
    name: "Bambu Lab P1P #4",
    status: "Maintenance",
    website: "https://bambulab.com/en/p1p",
    printHours: 398,
    maintenance: { next: 2, last: "2025-05-15" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.6mm Hardened Steel", available: ["0.2mm", "0.4mm", "0.8mm"] },
    currentPrint: null,
    loadedMaterials: [],
    usageHistory: [
      { day: "Mon", hours: 22 },
      { day: "Tue", hours: 22 },
      { day: "Wed", hours: 24 },
      { day: "Thu", hours: 23 },
      { day: "Fri", hours: 21 },
      { day: "Sat", hours: 18 },
      { day: "Sun", hours: 20 },
    ],
  },
  {
    id: "BAMBU-P1P-05",
    name: "Bambu Lab P1P #5",
    status: "Printing",
    website: "https://bambulab.com/en/p1p",
    printHours: 55,
    maintenance: { next: 145, last: "2025-06-30" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: {
      file: "pc_cable_combs.3mf",
      image: "/pc-cable-combs.png",
      progress: 25,
      timeElapsed: "0h 30m",
      timeRemaining: "1h 30m",
    },
    loadedMaterials: [{ slot: 1, materialId: "PETG-BLK-18", remaining: 180 }],
    usageHistory: [
      { day: "Mon", hours: 5 },
      { day: "Tue", hours: 8 },
      { day: "Wed", hours: 10 },
      { day: "Thu", hours: 7 },
      { day: "Fri", hours: 6 },
      { day: "Sat", hours: 12 },
      { day: "Sun", hours: 7 },
    ],
  },
  {
    id: "BAMBU-P1P-06",
    name: "Bambu Lab P1P #6",
    status: "Idle",
    website: "https://bambulab.com/en/p1p",
    printHours: 180,
    maintenance: { next: 20, last: "2025-06-20" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: null,
    loadedMaterials: [
      { slot: 1, materialId: "PLA-BLK-01", remaining: 750 },
      { slot: 2, materialId: "PLA-MBL-08", remaining: 450 },
      { slot: 3, materialId: "PLA-SLV-23", remaining: 650 },
    ],
    usageHistory: [
      { day: "Mon", hours: 20 },
      { day: "Tue", hours: 14 },
      { day: "Wed", hours: 15 },
      { day: "Thu", hours: 18 },
      { day: "Fri", hours: 22 },
      { day: "Sat", hours: 24 },
      { day: "Sun", hours: 17 },
    ],
  },
  {
    id: "BAMBU-P1P-07",
    name: "Bambu Lab P1P #7",
    status: "Printing",
    website: "https://bambulab.com/en/p1p",
    printHours: 412,
    maintenance: { next: 188, last: "2025-06-05" },
    bed: { type: "High Temp Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Hardened Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: {
      file: "drone_frame_v3.3mf",
      image: "/drone-frame.png",
      progress: 95,
      timeElapsed: "10h 5m",
      timeRemaining: "0h 20m",
    },
    loadedMaterials: [{ slot: 1, materialId: "ABS-CF-24", remaining: 120 }],
    usageHistory: [
      { day: "Mon", hours: 24 },
      { day: "Tue", hours: 24 },
      { day: "Wed", hours: 22 },
      { day: "Thu", hours: 23 },
      { day: "Fri", hours: 20 },
      { day: "Sat", hours: 18 },
      { day: "Sun", hours: 24 },
    ],
  },
  {
    id: "BAMBU-P1P-08",
    name: "Bambu Lab P1P #8",
    status: "Idle",
    website: "https://bambulab.com/en/p1p",
    printHours: 22,
    maintenance: { next: 178, last: "2025-06-30" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: null,
    loadedMaterials: [
      { slot: 1, materialId: "PLA-GLD-07", remaining: 850 },
      { slot: 2, materialId: "PLA-SLV-23", remaining: 650 },
    ],
    usageHistory: [
      { day: "Mon", hours: 2 },
      { day: "Tue", hours: 4 },
      { day: "Wed", hours: 3 },
      { day: "Thu", hours: 5 },
      { day: "Fri", hours: 2 },
      { day: "Sat", hours: 6 },
      { day: "Sun", hours: 0 },
    ],
  },
  {
    id: "BAMBU-P1P-09",
    name: "Bambu Lab P1P #9",
    status: "Printing",
    website: "https://bambulab.com/en/p1p",
    printHours: 3,
    maintenance: { next: 197, last: "2025-06-30" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: {
      file: "collapsing_katana.3mf",
      image: "/collapsing-katana.png",
      progress: 15,
      timeElapsed: "1h 0m",
      timeRemaining: "5h 40m",
    },
    loadedMaterials: [{ slot: 1, materialId: "PLA-SLV-23", remaining: 620 }],
    usageHistory: [
      { day: "Mon", hours: 0 },
      { day: "Tue", hours: 0 },
      { day: "Wed", hours: 0 },
      { day: "Thu", hours: 1 },
      { day: "Fri", hours: 2 },
      { day: "Sat", hours: 0 },
      { day: "Sun", hours: 0 },
    ],
  },
  {
    id: "BAMBU-P1P-10",
    name: "Bambu Lab P1P #10",
    status: "Maintenance",
    website: "https://bambulab.com/en/p1p",
    printHours: 599,
    maintenance: { next: 1, last: "2025-05-01" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: null,
    loadedMaterials: [],
    usageHistory: [
      { day: "Mon", hours: 24 },
      { day: "Tue", hours: 24 },
      { day: "Wed", hours: 24 },
      { day: "Thu", hours: 24 },
      { day: "Fri", hours: 23 },
      { day: "Sat", hours: 24 },
      { day: "Sun", hours: 24 },
    ],
  },
  {
    id: "BAMBU-P1P-11",
    name: "Bambu Lab P1P #11",
    status: "Idle",
    website: "https://bambulab.com/en/p1p",
    printHours: 89,
    maintenance: { next: 111, last: "2025-06-28" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: null,
    loadedMaterials: [
      { slot: 1, materialId: "PLA-WD-09", remaining: 600 },
      { slot: 2, materialId: "PLA-MRB-11", remaining: 950 },
    ],
    usageHistory: [
      { day: "Mon", hours: 10 },
      { day: "Tue", hours: 12 },
      { day: "Wed", hours: 14 },
      { day: "Thu", hours: 8 },
      { day: "Fri", hours: 11 },
      { day: "Sat", hours: 13 },
      { day: "Sun", hours: 21 },
    ],
  },
  {
    id: "BAMBU-P1P-12",
    name: "Bambu Lab P1P #12",
    status: "Printing",
    website: "https://bambulab.com/en/p1p",
    printHours: 12,
    maintenance: { next: 188, last: "2025-06-30" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: {
      file: "gridfinity_base_4x4.3mf",
      image: "/gridfinity-base.png",
      progress: 40,
      timeElapsed: "2h 10m",
      timeRemaining: "3h 15m",
    },
    loadedMaterials: [{ slot: 1, materialId: "PETG-YLW-21", remaining: 80 }],
    usageHistory: [
      { day: "Mon", hours: 1 },
      { day: "Tue", hours: 2 },
      { day: "Wed", hours: 1 },
      { day: "Thu", hours: 3 },
      { day: "Fri", hours: 2 },
      { day: "Sat", hours: 2 },
      { day: "Sun", hours: 1 },
    ],
  },
  {
    id: "BAMBU-P1P-13",
    name: "Bambu Lab P1P #13",
    status: "Idle",
    website: "https://bambulab.com/en/p1p",
    printHours: 270,
    maintenance: { next: 130, last: "2025-06-12" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: null,
    loadedMaterials: [
      { slot: 1, materialId: "PLA-PRO-22", remaining: 980 },
      { slot: 2, materialId: "ABS-CF-24", remaining: 400 },
    ],
    usageHistory: [
      { day: "Mon", hours: 23 },
      { day: "Tue", hours: 19 },
      { day: "Wed", hours: 21 },
      { day: "Thu", hours: 20 },
      { day: "Fri", hours: 18 },
      { day: "Sat", hours: 22 },
      { day: "Sun", hours: 24 },
    ],
  },
  {
    id: "BAMBU-P1P-14",
    name: "Bambu Lab P1P #14",
    status: "Printing",
    website: "https://bambulab.com/en/p1p",
    printHours: 450,
    maintenance: { next: 150, last: "2025-06-01" },
    bed: { type: "High Temp Plate", size: "256x256mm" },
    nozzles: { current: "0.8mm Hardened Steel", available: ["0.2mm", "0.4mm", "0.6mm"] },
    currentPrint: {
      file: "hydroponic_tower.3mf",
      image: "/hydroponic-tower.png",
      progress: 78,
      timeElapsed: "14h 0m",
      timeRemaining: "4h 0m",
    },
    loadedMaterials: [{ slot: 1, materialId: "PC-CLR-06", remaining: 450 }],
    usageHistory: [
      { day: "Mon", hours: 24 },
      { day: "Tue", hours: 24 },
      { day: "Wed", hours: 24 },
      { day: "Thu", hours: 22 },
      { day: "Fri", hours: 23 },
      { day: "Sat", hours: 24 },
      { day: "Sun", hours: 24 },
    ],
  },
  {
    id: "BAMBU-P1P-15",
    name: "Bambu Lab P1P #15",
    status: "Idle",
    website: "https://bambulab.com/en/p1p",
    printHours: 15,
    maintenance: { next: 185, last: "2025-06-30" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: null,
    loadedMaterials: [],
    usageHistory: [
      { day: "Mon", hours: 1 },
      { day: "Tue", hours: 1 },
      { day: "Wed", hours: 2 },
      { day: "Thu", hours: 3 },
      { day: "Fri", hours: 2 },
      { day: "Sat", hours: 4 },
      { day: "Sun", hours: 2 },
    ],
  },
  {
    id: "BAMBU-P1P-16",
    name: "Bambu Lab P1P #16",
    status: "Printing",
    website: "https://bambulab.com/en/p1p",
    printHours: 99,
    maintenance: { next: 101, last: "2025-06-29" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.2mm Stainless Steel", available: ["0.4mm", "0.6mm", "0.8mm"] },
    currentPrint: {
      file: "miniature_dnd_figures.3mf",
      image: "/dnd-miniatures.png",
      progress: 50,
      timeElapsed: "3h 30m",
      timeRemaining: "3h 30m",
    },
    loadedMaterials: [{ slot: 1, materialId: "PLA-PRO-22", remaining: 920 }],
    usageHistory: [
      { day: "Mon", hours: 12 },
      { day: "Tue", hours: 10 },
      { day: "Wed", hours: 15 },
      { day: "Thu", hours: 13 },
      { day: "Fri", hours: 11 },
      { day: "Sat", hours: 14 },
      { day: "Sun", hours: 24 },
    ],
  },
  {
    id: "BAMBU-P1P-17",
    name: "Bambu Lab P1P #17",
    status: "Idle",
    website: "https://bambulab.com/en/p1p",
    printHours: 320,
    maintenance: { next: 80, last: "2025-06-11" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: null,
    loadedMaterials: [
      { slot: 1, materialId: "PETG-RED-19", remaining: 780 },
      { slot: 2, materialId: "PETG-BLU-20", remaining: 550 },
    ],
    usageHistory: [
      { day: "Mon", hours: 22 },
      { day: "Tue", hours: 21 },
      { day: "Wed", hours: 23 },
      { day: "Thu", hours: 20 },
      { day: "Fri", hours: 19 },
      { day: "Sat", hours: 24 },
      { day: "Sun", hours: 24 },
    ],
  },
  {
    id: "BAMBU-P1P-18",
    name: "Bambu Lab P1P #18",
    status: "Printing",
    website: "https://bambulab.com/en/p1p",
    printHours: 175,
    maintenance: { next: 25, last: "2025-06-22" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: {
      file: "bento_box_organizer.3mf",
      image: "/bento-box.png",
      progress: 33,
      timeElapsed: "2h 45m",
      timeRemaining: "5h 30m",
    },
    loadedMaterials: [
      { slot: 1, materialId: "PLA-WD-09", remaining: 510 },
      { slot: 2, materialId: "PLA-BLK-01", remaining: 750 },
    ],
    usageHistory: [
      { day: "Mon", hours: 18 },
      { day: "Tue", hours: 20 },
      { day: "Wed", hours: 17 },
      { day: "Thu", hours: 19 },
      { day: "Fri", hours: 21 },
      { day: "Sat", hours: 23 },
      { day: "Sun", hours: 22 },
    ],
  },
  {
    id: "BAMBU-P1P-19",
    name: "Bambu Lab P1P #19",
    status: "Idle",
    website: "https://bambulab.com/en/p1p",
    printHours: 4,
    maintenance: { next: 196, last: "2025-06-30" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: null,
    loadedMaterials: [],
    usageHistory: [
      { day: "Mon", hours: 0 },
      { day: "Tue", hours: 1 },
      { day: "Wed", hours: 0 },
      { day: "Thu", hours: 2 },
      { day: "Fri", hours: 1 },
      { day: "Sat", hours: 0 },
      { day: "Sun", hours: 0 },
    ],
  },
  {
    id: "BAMBU-P1P-20",
    name: "Bambu Lab P1P #20",
    status: "Printing",
    website: "https://bambulab.com/en/p1p",
    printHours: 290,
    maintenance: { next: 110, last: "2025-06-14" },
    bed: { type: "Textured PEI Plate", size: "256x256mm" },
    nozzles: { current: "0.4mm Stainless Steel", available: ["0.2mm", "0.6mm", "0.8mm"] },
    currentPrint: {
      file: "gopro_mount_set.3mf",
      image: "/gopro-mount.png",
      progress: 88,
      timeElapsed: "1h 45m",
      timeRemaining: "0h 15m",
    },
    loadedMaterials: [{ slot: 1, materialId: "PETG-GRN-25", remaining: 780 }],
    usageHistory: [
      { day: "Mon", hours: 21 },
      { day: "Tue", hours: 20 },
      { day: "Wed", hours: 22 },
      { day: "Thu", hours: 18 },
      { day: "Fri", hours: 24 },
      { day: "Sat", hours: 23 },
      { day: "Sun", hours: 19 },
    ],
  },
]

export const storageBins = [
  {
    id: "shelf-a-1",
    name: "Shelf A, Bin 1",
    contents: ["PLA Black", "PLA Silk Silver"],
    status: "OK",
    features: [],
    history: [
      { time: "10:00", temp: 22, humidity: 58 },
      { time: "11:00", temp: 23, humidity: 57 },
      { time: "12:00", temp: 23, humidity: 57 },
      { time: "13:00", temp: 22, humidity: 59 },
      { time: "14:00", temp: 22, humidity: 60 },
    ],
  },
  {
    id: "shelf-a-2",
    name: "Shelf A, Bin 2",
    contents: ["PLA Silk Gold", "PLA Marble"],
    status: "OK",
    features: [],
    history: [],
  },
  {
    id: "shelf-a-3",
    name: "Shelf A, Bin 3",
    contents: ["PLA Matte Blue", "PLA+ Pro Grey"],
    status: "OK",
    features: [],
    history: [],
  },
  {
    id: "shelf-b-1",
    name: "Shelf B, Bin 1",
    contents: ["PLA Wood", "PETG Yellow", "PLA Rainbow"],
    status: "OK",
    features: [],
    history: [],
  },
  {
    id: "shelf-b-2",
    name: "Shelf B, Bin 2",
    contents: ["PETG White"],
    status: "OK",
    features: [],
    history: [
      { time: "10:00", temp: 22, humidity: 55 },
      { time: "11:00", temp: 22, humidity: 56 },
      { time: "12:00", temp: 23, humidity: 55 },
      { time: "13:00", temp: 23, humidity: 54 },
      { time: "14:00", temp: 22, humidity: 55 },
    ],
  },
  {
    id: "shelf-b-3",
    name: "Shelf B, Bin 3",
    contents: ["PETG Clear", "PETG Black"],
    status: "OK",
    features: [],
    history: [],
  },
  {
    id: "shelf-c-1",
    name: "Shelf C, Bin 1",
    contents: ["PLA Glow-in-the-Dark", "PETG Green"],
    status: "OK",
    features: [],
    history: [],
  },
  {
    id: "shelf-c-2",
    name: "Shelf C, Bin 2",
    contents: ["PETG Red", "PETG Blue"],
    status: "OK",
    features: [],
    history: [],
  },
  {
    id: "drybox-1",
    name: "DryBox 1",
    contents: ["ABS Red", "ABS Blue", "PVA Natural", "PC Clear", "ABS Orange", "ABS Natural"],
    status: "Dry",
    features: ["Active Drying", "Direct Feed"],
    history: [
      { time: "10:00", temp: 45, humidity: 15 },
      { time: "11:00", temp: 45, humidity: 14 },
      { time: "12:00", temp: 46, humidity: 14 },
      { time: "13:00", temp: 45, humidity: 13 },
      { time: "14:00", temp: 45, humidity: 13 },
    ],
  },
  {
    id: "drybox-2",
    name: "DryBox 2",
    contents: ["ABS Green", "ABS Grey", "ABS Pink", "ABS Carbon Fiber"],
    status: "Dry",
    features: ["Active Drying"],
    history: [],
  },
  {
    id: "cabinet-3",
    name: "Cabinet 3",
    contents: ["Standard Resin Grey"],
    status: "OK",
    features: ["UV Protection"],
    history: [
      { time: "10:00", temp: 21, humidity: 50 },
      { time: "11:00", temp: 21, humidity: 51 },
      { time: "12:00", temp: 22, humidity: 50 },
      { time: "13:00", temp: 22, humidity: 49 },
      { time: "14:00", temp: 21, humidity: 50 },
    ],
  },
  {
    id: "cabinet-1",
    name: "Cabinet 1",
    contents: ["Tough Resin Black", "Flexible Resin Clear", "High Temp Resin Amber"],
    status: "OK",
    features: ["UV Protection"],
    history: [],
  },
  {
    id: "cabinet-2",
    name: "Cabinet 2",
    contents: ["Castable Wax Resin Purple", "Dental Model Resin Beige"],
    status: "OK",
    features: ["UV Protection", "Temp Controlled"],
    history: [],
  },
  {
    id: "cabinet-4",
    name: "Cabinet 4",
    contents: ["Water Washable Resin White", "ABS-Like Resin Grey", "Fast Curing Resin Red"],
    status: "OK",
    features: ["UV Protection"],
    history: [],
  },
  {
    id: "cabinet-5",
    name: "Cabinet 5",
    contents: ["Plant-based Eco Resin Green", "8K Aqua Resin Grey"],
    status: "OK",
    features: ["UV Protection"],
    history: [],
  },
]

export const logs = [
  {
    id: 1,
    material: "PLA Black",
    machine: "Ender 3 V2",
    amount: 50,
    nfc: true,
    user: "Operator 1",
    timestamp: "2025-06-30 14:00",
  },
  {
    id: 2,
    material: "ABS Red",
    machine: "Bambu Lab X1C",
    amount: 120,
    nfc: true,
    user: "Operator 1",
    timestamp: "2025-06-30 11:30",
  },
  {
    id: 3,
    material: "PETG White",
    machine: "Prusa MK3S+",
    amount: 25,
    nfc: false,
    user: "Operator 2",
    timestamp: "2025-06-30 09:00",
  },
  {
    id: 4,
    material: "ABS Carbon Fiber",
    machine: "Bambu Lab P1P #7",
    amount: 280,
    nfc: true,
    user: "Operator 1",
    timestamp: "2025-06-29 22:15",
  },
  {
    id: 5,
    material: "PLA Rainbow",
    machine: "Bambu Lab P1P #2",
    amount: 140,
    nfc: true,
    user: "Operator 2",
    timestamp: "2025-06-29 18:45",
  },
  {
    id: 6,
    material: "PC Clear",
    machine: "Bambu Lab P1P #14",
    amount: 350,
    nfc: true,
    user: "Operator 1",
    timestamp: "2025-06-29 15:00",
  },
  {
    id: 7,
    material: "PLA Pro Grey",
    machine: "Bambu Lab P1P #16",
    amount: 60,
    nfc: false,
    user: "Operator 2",
    timestamp: "2025-06-29 11:20",
  },
  {
    id: 8,
    material: "Standard Resin Grey",
    machine: "Elegoo Saturn 4K",
    amount: 75,
    nfc: false,
    user: "Operator 1",
    timestamp: "2025-06-28 20:05",
  },
  {
    id: 9,
    material: "PETG Yellow",
    machine: "Bambu Lab P1P #12",
    amount: 40,
    nfc: true,
    user: "Operator 2",
    timestamp: "2025-06-28 16:30",
  },
  {
    id: 10,
    material: "PLA Wood",
    machine: "Bambu Lab P1P #18",
    amount: 90,
    nfc: true,
    user: "Operator 1",
    timestamp: "2025-06-28 12:00",
  },
  {
    id: 11,
    material: "ABS-Like Resin Grey",
    machine: "Elegoo Saturn 4K",
    amount: 125,
    nfc: false,
    user: "Operator 2",
    timestamp: "2025-06-28 09:50",
  },
  {
    id: 12,
    material: "PLA Silk Silver",
    machine: "Bambu Lab P1P #9",
    amount: 30,
    nfc: true,
    user: "Operator 1",
    timestamp: "2025-06-27 23:00",
  },
  {
    id: 13,
    material: "PETG Green",
    machine: "Bambu Lab P1P #20",
    amount: 40,
    nfc: true,
    user: "Operator 2",
    timestamp: "2025-06-27 19:10",
  },
  {
    id: 14,
    material: "ABS Blue",
    machine: "Bambu Lab X1C",
    amount: 50,
    nfc: true,
    user: "Operator 1",
    timestamp: "2025-06-27 14:30",
  },
  {
    id: 15,
    material: "PLA Matte Blue",
    machine: "Bambu Lab P1P #1",
    amount: 15,
    nfc: false,
    user: "Operator 2",
    timestamp: "2025-06-27 10:00",
  },
  {
    id: 16,
    material: "Tough Resin Black",
    machine: "Elegoo Saturn 4K",
    amount: 200,
    nfc: false,
    user: "Operator 1",
    timestamp: "2025-06-26 17:45",
  },
  {
    id: 17,
    material: "PETG Red",
    machine: "Bambu Lab P1P #17",
    amount: 70,
    nfc: true,
    user: "Operator 2",
    timestamp: "2025-06-26 13:00",
  },
  {
    id: 18,
    material: "ABS Orange",
    machine: "Bambu Lab P1P #8",
    amount: 20,
    nfc: false,
    user: "Operator 1",
    timestamp: "2025-06-26 08:20",
  },
  {
    id: 19,
    material: "PETG Black",
    machine: "Bambu Lab P1P #3",
    amount: 80,
    nfc: true,
    user: "Operator 2",
    timestamp: "2025-06-25 18:00",
  },
  {
    id: 20,
    material: "PLA Glow-in-the-Dark",
    machine: "Prusa MK3S+",
    amount: 110,
    nfc: false,
    user: "Operator 1",
    timestamp: "2025-06-25 15:30",
  },
]
